version: "2.0"

services:
    app:
        build:
            dockerfile: ./Dockerfile
            context: .
        ports:
            - "5000:80"
        depends_on:
            - mongodb
    mongodb:
        image: mongo:4.0
        volumes: 
            - ./database:/data/db
