export default {
    CHANGE_CLOCK: "CHANGE_CLOCK",
    CHANGE_DARKMODE: "CHANGE_DARKMODE",
    SAVE_PREFERENCES: "SAVE_PREFERENCES",
    GET_PREFERENCES: "GET_PREFERENCES", 
    CHANGE_BACKGROUND_IMAGE: "CHANGE_BACKGROUND_IMAGE",
    REMOVE_BACKGROUND_IMAGE: "REMOVE_BACKGROUND_IMAGE", 
}