export default {
    ADD_WEBLINK: "ADD_WEBLINK",
    DELETE_WEBLINK: "DELETE_WEBLINK",
    DELETE_WEBLINKS: "DELETE_WEBLINKS",
    REPLACE_WEBLINK: "REPLACE_WEBLINK",
    GET_WEBLINKS: "GET_WEBLINKS",
    GET_WEBLINK: "GET_WEBLINK",
}