export default {
    ADD_NOTE: "ADD_NOTE",
    REMOVE_NOTE: "REMOVE_NOTE",
    REMOVE_NOTES: "REMOVE_NOTES",
    REPLACE_NOTE: "REPLACE_NOTE",
    GET_NOTES: "GET_NOTES",
    GET_NOTE: "GET_NOTE",
    PASS_NOTE: "PASS_NOTE",
}