version: '3.4'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mercury
    ports:
      - 27017-27019:27017-27019
  mercury:
    image: mercury/api
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    depends_on:
        - mongo
    ports:
      - 8393:8393
